const data = {
  products: [
    {
      name: "Nike Slim",
      slug: "nike-slim",
      category: "Shirts",
      image: "images/",
      price: "300",
      countInStock: 10,
      brand: "",
      rating: "",
      numReviews: 10,
      description: "",
    },
    {
      name: "Adidas Fit",
      slug: "adidas-fit",
      category: "Shirts",
      image: "images/",
      price: "150",
      countInStock: 10,
      brand: "",
      rating: "",
      numReviews: 10,
      description: "",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Shirts",
      image: "images/",
      price: "",
      countInStock: 10,
      brand: "",
      rating: "",
      numReviews: 10,
      description: "",
    },
    {
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      category: "Shirts",
      image: "images/",
      price: "150",
      countInStock: 10,
      brand: "",
      rating: "",
      numReviews: 10,
      description: "",
    },
  ],
};
